### ISSUE TITLE
Company Outreach Email Templates

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/volunteers#34]
Create a generalized template for reaching out to companies.

The email should say
- what the ccss is
- why we're reaching out... (tech talks, event collaboration)
- what's in it for them ... (recruitment, cheaper than Carleton Coop)

**Comment by richard-dh-kim** [comment]
Email Template (Draft):
https://docs.google.com/document/d/12MNw96x40uCdi3vsCYAfQktYQHAUDl1s8npXggB1h1Q/edit?usp=sharing

Outreach Tracker:
https://docs.google.com/spreadsheets/d/1J48bO2DnDp-sRGoBR8zufzmToqFR74ManCZtg8vadu4/edit?usp=sharing
