### ISSUE TITLE
Initial Merch drop shipping Investigation

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/volunteers#47]
Let's make a spreadsheet that compares various drop shipping platforms.

Some platforms that exist
- Gelato - Matthew tried this one a year ago and was not happy with the printing quality, maybe they have improved in the past year
- Printful - Matthew tried this one a year ago and thought their embroidery was good, his hat + tshirt are drop shipped
- Printify
- Gooten

For each platform, we should list out 
- what products they offer 
- what price 
- what cost with shipping
- available in Canada (varies by product)?

We should present this in either a BOD meeting and or a discussion solely for merch

**Comment by ryangchung** [comment]
Anyone else interested in this investigation should assign themselves to this issue, discussion can happen in the `#merch` channel!
