### ISSUE TITLE
List of Ottawa Tech Companies

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/volunteers#79]
Please create a prioritized list of Ottawa tech companies that we will split up amongst the team to find the contacts for.

Notes like whether the company often hires from Carleton or has previously hired students would be cool!

**Comment by richard-dh-kim** [comment]
Done:
https://docs.google.com/spreadsheets/d/1_Cszgl3Iu-cwHPrldq4j21zDdyKZyJURcjD9LKOomuE/edit?gid=0#gid=0

**Comment by richard-dh-kim** [comment]
Done:
https://docs.google.com/spreadsheets/d/1_Cszgl3Iu-cwHPrldq4j21zDdyKZyJURcjD9LKOomuE/edit?gid=0#gid=0
